/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/concurrency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["ConcurrencyPoliciesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/concurrency/prune": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["PruneResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/concurrency/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["ConcurrencyReconcileResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/concurrency/{prefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    prefix: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["ConcurrencyPolicyUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["ConcurrencyPolicyView"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `prefix` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/concurrency/{prefix}/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    prefix: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["ConcurrencyKeysResponse"];
                    };
                };
                /** @description Invalid `offset` or `limit` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `prefix` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cron/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    queue?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CronSchedulesResponse"];
                    };
                };
                /** @description Invalid `queue` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cron/schedules/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["CronScheduleUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["CronScheduleView"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `name` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/cron/schedules/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `name` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent stream of job events
         * @description Streams an event per insert, update, delete and dead-letter, as they happen. Each event names its queue and the job id. A dead-letter event carries the id the job had in its queue and sets dlq. The stream starts with one "connected" event. Sends a keepalive comment every 15 seconds. A server with streaming switched off answers one "disabled" event and closes.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description An event stream. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": {
                            /** @description The event comes from the DLQ table. */
                            dlq?: boolean;
                            /** @enum {string} */
                            event: "job_inserted" | "job_updated" | "job_deleted" | "job_dlq" | "connected" | "disabled";
                            /** @description The job id. A DLQ row gives the id of the job it holds. */
                            job_id?: number;
                            message?: string;
                            /** @description The queue name. */
                            table?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["LivenessResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["MaintenanceResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    parent_id?: number;
                    job_id?: number;
                    group_key?: string;
                    kind?: string;
                    payload?: string;
                    completed_after?: string;
                    completed_before?: string;
                    sort_by?: "id" | "completed_at" | "inserted_at" | "job_id" | "attempts" | "group_key" | "parent_id";
                    sort_dir?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["ArchiveResponse_AnyJson"];
                    };
                };
                /** @description Invalid `sort_dir` or `sort_by` or `completed_before` or `completed_after` or `payload` or `kind` or `group_key` or `job_id` or `parent_id` or `offset` or `limit` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/archive/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["BatchDeleteRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["BatchDeleteResponse"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/archive/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/archive/{id}/reenqueue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            /** @description Optional. A payload replaces the stored payload, and the kind, rate-limit and concurrency columns come from it again. An empty body keeps the stored payload. */
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["PayloadEdit_AnyJson"];
                };
            };
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["ClaimRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["ClaimResponse_AnyJson"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/dlq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    parent_id?: number;
                    job_id?: number;
                    group_key?: string;
                    kind?: string;
                    payload?: string;
                    error?: string;
                    sort_by?: "id" | "failed_at" | "job_id" | "priority" | "attempts" | "inserted_at" | "group_key" | "parent_id" | "last_attempted_at";
                    sort_dir?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["DLQResponse_AnyJson"];
                    };
                };
                /** @description Invalid `sort_dir` or `sort_by` or `error` or `payload` or `kind` or `group_key` or `job_id` or `parent_id` or `offset` or `limit` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/dlq/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["BatchDeleteRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["BatchDeleteResponse"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/dlq/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/dlq/{id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            /** @description Optional. A payload replaces the stored payload, and the kind, rate-limit and concurrency columns come from it again. An empty body keeps the stored payload. */
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["PayloadEdit_AnyJson"];
                };
            };
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    group_key?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["GroupsResponse"];
                    };
                };
                /** @description Invalid `group_key` or `offset` or `limit` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    group_key?: string;
                    parent_id?: number;
                    job_id?: number;
                    roots_only?: boolean;
                    status?: "ready" | "in_flight" | "backoff" | "scheduled" | "suspended" | "throttled" | "cancelled" | "exhausted";
                    claimed_by?: string;
                    kind?: string;
                    payload?: string;
                    rate_limit_prefix?: string;
                    concurrency_prefix?: string;
                    sort_by?: "id" | "priority" | "attempts" | "inserted_at" | "not_visible_until" | "group_key" | "parent_id" | "last_attempted_at";
                    sort_dir?: "asc" | "desc";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["JobsResponse_AnyJson"];
                    };
                };
                /** @description Invalid `sort_dir` or `sort_by` or `concurrency_prefix` or `rate_limit_prefix` or `payload` or `kind` or `claimed_by` or `status` or `roots_only` or `job_id` or `parent_id` or `group_key` or `offset` or `limit` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["JobWrite_AnyJson"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["JobResponse_AnyJson"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["BatchInsertRequest_AnyJson"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["BatchInsertResponse_AnyJson"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["JobWithStatusResponse_AnyJson"];
                    };
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/{id}/ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["AckRequest_AnyJson"];
                };
            };
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/{id}/extend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["ExtendRequest"];
                };
            };
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/{id}/force-cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/{id}/move-to-dlq": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/{id}/nack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["JobLease"];
                };
            };
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/{id}/pause-children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/{id}/promote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/{id}/reschedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["RescheduleRequest"];
                };
            };
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/{id}/resume-children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/jobs/{id}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": string[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queue/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["StatsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["QueuesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queues/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["AllStatsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queues/{queue}/details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    queue: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["QueueRow"];
                    };
                };
                /** @description `queue` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queues/{queue}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    queue: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `queue` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/queues/{queue}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    queue: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `queue` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rate-limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["RateLimitPoliciesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rate-limits/prune": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    idle?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["PruneResponse"];
                    };
                };
                /** @description Invalid `idle` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rate-limits/{prefix}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    prefix: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["RateLimitPolicyUpdate"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["RateLimitPolicyView"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `prefix` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/v1/rate-limits/{prefix}/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    prefix: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["RateLimitBucketsResponse"];
                    };
                };
                /** @description Invalid `offset` or `limit` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `prefix` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rate-limits/{prefix}/buckets/{key}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    prefix: string;
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json;charset=utf-8": components["schemas"]["AddTokensRequest"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["AddTokensResponse"];
                    };
                };
                /** @description Invalid `body` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `prefix` or `key` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rate-limits/{prefix}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    prefix: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["RateLimitResetResponse"];
                    };
                };
                /** @description `prefix` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    queue?: string;
                    live?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json;charset=utf-8": components["schemas"]["WorkersResponse"];
                    };
                };
                /** @description Invalid `live` or `queue` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workers/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description `id` not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AckRequest_AnyJson: {
            /** Format: int64 */
            claimSeq: number;
            claimedBy: components["schemas"]["UUID"];
            result?: components["schemas"]["AnyJson"] | (never | null);
        };
        AddTokensRequest: {
            /** Format: double */
            tokens: number;
        };
        AddTokensResponse: {
            /** Format: int64 */
            woken: number;
        };
        AllStatsResponse: {
            queues: components["schemas"]["QueueOverview"][];
        };
        /** @description Caller-defined JSON. */
        AnyJson: unknown;
        ArchiveEntry_AnyJson: {
            /** Format: int64 */
            archivePrimaryKey: number;
            completedAt: components["schemas"]["UTCTime"];
            jobSnapshot: components["schemas"]["Job_AnyJson"];
            result: components["schemas"]["AnyJson"] | (never | null);
        };
        ArchiveResponse_AnyJson: {
            items: components["schemas"]["ArchiveEntry_AnyJson"][];
            limit: number;
            offset: number;
            total: number;
        };
        BatchDeleteRequest: {
            ids: number[];
        };
        BatchDeleteResponse: {
            /** Format: int64 */
            deleted: number;
        };
        BatchInsertRequest_AnyJson: {
            jobWrites: components["schemas"]["JobWrite_AnyJson"][];
        };
        BatchInsertResponse_AnyJson: {
            inserted: components["schemas"]["Job_AnyJson"][];
            insertedCount: number;
        };
        ClaimRequest: {
            /** Format: double */
            leaseSeconds?: number | null;
            maxJobs?: number | null;
        };
        ClaimResponse_AnyJson: {
            jobs: components["schemas"]["Job_AnyJson"][];
        };
        ConcurrencyKey: {
            prefix: string;
            suffix: string;
        };
        ConcurrencyKeyView: {
            /** Format: int32 */
            effectiveLimit: number;
            /** Format: double */
            fillFraction: number | null;
            /** Format: int32 */
            inFlight: number;
            key: string;
            prefix: string;
        };
        ConcurrencyKeysResponse: {
            items: components["schemas"]["ConcurrencyKeyView"][];
        };
        ConcurrencyPoliciesResponse: {
            policies: components["schemas"]["ConcurrencyPolicyView"][];
        };
        ConcurrencyPolicyUpdate: {
            /** Format: int32 */
            overrideLimit?: number | null;
        };
        ConcurrencyPolicyView: {
            /** Format: int32 */
            defaultLimit: number;
            /** Format: int64 */
            keyCount: number;
            /** Format: int32 */
            maxInFlight?: number | null;
            /** Format: int32 */
            overrideLimit?: number | null;
            prefix: string;
            /** Format: int64 */
            totalInFlight: number;
        };
        ConcurrencyReconcileResponse: {
            /** Format: int64 */
            reconciled: number;
        };
        CronScheduleRow: {
            createdAt: components["schemas"]["UTCTime"];
            defaultExpression: string;
            defaultOverlap: string;
            defaultTimezone?: string | null;
            enabled: boolean;
            lastCheckedAt?: components["schemas"]["UTCTime"] | (never | null);
            lastFiredAt?: components["schemas"]["UTCTime"] | (never | null);
            lastManualRunAt?: components["schemas"]["UTCTime"] | (never | null);
            name: string;
            overrideExpression?: string | null;
            overrideOverlap?: string | null;
            overrideTimezone?: string | null;
            queueName: string;
            runRequestedAt?: components["schemas"]["UTCTime"] | (never | null);
            updatedAt: components["schemas"]["UTCTime"];
        };
        CronScheduleUpdate: {
            enabled?: boolean | null;
            overrideExpression?: string | null;
            overrideOverlap?: string | null;
            overrideTimezone?: string | null;
        };
        /** @description A schedule row plus the next tick it fires at. It is null when the schedule is disabled or has no next tick. */
        CronScheduleView: components["schemas"]["CronScheduleRow"] & {
            nextRunAt: components["schemas"]["UTCTime"] | (never | null);
        };
        CronSchedulesResponse: {
            cronSchedules: components["schemas"]["CronScheduleView"][];
        };
        DLQEntry_AnyJson: {
            /** Format: int64 */
            dlqPrimaryKey: number;
            failedAt: components["schemas"]["UTCTime"];
            jobSnapshot: components["schemas"]["Job_AnyJson"];
        };
        DLQResponse_AnyJson: {
            items: components["schemas"]["DLQEntry_AnyJson"][];
            limit: number;
            offset: number;
            total: number;
        };
        DedupKey: {
            key: string;
            /** @enum {string} */
            strategy: "ignore" | "replace";
        };
        ExtendRequest: {
            /** Format: int64 */
            claimSeq: number;
            claimedBy: components["schemas"]["UUID"];
            /** Format: double */
            seconds: number;
        };
        GroupSummary: {
            groupKey: string;
            headBlocked: boolean;
            /** Format: int64 */
            headJobId: number | null;
            headStatus: components["schemas"]["JobStatus"] | (never | null);
            inFlight: boolean;
            inFlightUntil: components["schemas"]["UTCTime"] | (never | null);
            /** Format: int64 */
            jobCount: number;
            nextDue: components["schemas"]["UTCTime"] | (never | null);
            /** Format: int64 */
            readyCount: number;
        };
        GroupsResponse: {
            items: components["schemas"]["GroupSummary"][];
            limit: number;
            offset: number;
            total: number;
        };
        HealthResponse: {
            checkedAt: components["schemas"]["UTCTime"];
            db?: components["schemas"]["PgDbHealth"] | (never | null);
            /** Format: double */
            dbLatencyMs?: number | null;
            schemaName: string;
            status: components["schemas"]["HealthStatus"];
        };
        /** @enum {string} */
        HealthStatus: "ok" | "down";
        JobLease: {
            /** Format: int64 */
            claimSeq: number;
            claimedBy: components["schemas"]["UUID"];
        };
        JobResponse_AnyJson: {
            job: components["schemas"]["Job_AnyJson"];
        };
        /** @enum {string} */
        JobStatus: "ready" | "in_flight" | "backoff" | "scheduled" | "suspended" | "throttled" | "cancelled" | "exhausted";
        JobWithStatusResponse_AnyJson: {
            job: components["schemas"]["JobWithStatus_AnyJson"];
        };
        JobWithStatus_AnyJson: {
            /** Format: int32 */
            archiveFor: number | null;
            /** Format: int32 */
            attempts: number;
            /** Format: int64 */
            claimSeq: number;
            claimedBy: components["schemas"]["UUID"] | (never | null);
            concurrency: components["schemas"]["ConcurrencyKey"] | (never | null);
            dedupKey: components["schemas"]["DedupKey"] | (never | null);
            groupKey: string | null;
            insertedAt: components["schemas"]["UTCTime"];
            isRollup: boolean;
            kind: string | null;
            lastAttemptedAt: components["schemas"]["UTCTime"] | (never | null);
            lastError: string | null;
            /** Format: int32 */
            maxAttempts: number | null;
            notVisibleUntil: components["schemas"]["UTCTime"] | (never | null);
            /** Format: int64 */
            parentId: number | null;
            parentState: components["schemas"]["AnyJson"] | (never | null);
            payload: components["schemas"]["AnyJson"];
            /** Format: int64 */
            primaryKey: number;
            /** Format: int32 */
            priority: number;
            queueName: string;
            rateLimit: components["schemas"]["RateLimitKey"] | (never | null);
            status: components["schemas"]["JobStatus"];
            suspended: boolean;
            traceparent: string | null;
            tracestate: string | null;
            updatedAt: components["schemas"]["UTCTime"] | (never | null);
        };
        JobWrite_AnyJson: {
            /** Format: int32 */
            archiveFor?: number | null;
            dedupKey?: components["schemas"]["DedupKey"] | (never | null);
            groupKey?: string | null;
            /** Format: int32 */
            maxAttempts?: number | null;
            notVisibleUntil?: components["schemas"]["UTCTime"] | (never | null);
            payload: components["schemas"]["AnyJson"];
            /** Format: int32 */
            priority?: number;
        };
        Job_AnyJson: {
            /** Format: int32 */
            archiveFor: number | null;
            /** Format: int32 */
            attempts: number;
            /** Format: int64 */
            claimSeq: number;
            claimedBy: components["schemas"]["UUID"] | (never | null);
            concurrency: components["schemas"]["ConcurrencyKey"] | (never | null);
            dedupKey: components["schemas"]["DedupKey"] | (never | null);
            groupKey: string | null;
            insertedAt: components["schemas"]["UTCTime"];
            isRollup: boolean;
            kind: string | null;
            lastAttemptedAt: components["schemas"]["UTCTime"] | (never | null);
            lastError: string | null;
            /** Format: int32 */
            maxAttempts: number | null;
            notVisibleUntil: components["schemas"]["UTCTime"] | (never | null);
            /** Format: int64 */
            parentId: number | null;
            parentState: components["schemas"]["AnyJson"] | (never | null);
            payload: components["schemas"]["AnyJson"];
            /** Format: int64 */
            primaryKey: number;
            /** Format: int32 */
            priority: number;
            queueName: string;
            rateLimit: components["schemas"]["RateLimitKey"] | (never | null);
            suspended: boolean;
            traceparent: string | null;
            tracestate: string | null;
            updatedAt: components["schemas"]["UTCTime"] | (never | null);
        };
        JobsResponse_AnyJson: {
            childCounts: {
                [key: string]: number;
            };
            dlqChildCounts: {
                [key: string]: number;
            };
            items: components["schemas"]["JobWithStatus_AnyJson"][];
            limit: number;
            offset: number;
            pausedParents: number[];
            total: number;
        };
        LivenessResponse: {
            alive: boolean;
        };
        MaintenanceResponse: {
            failed: string[];
            ops: {
                [key: string]: number;
            };
        };
        PayloadEdit_AnyJson: {
            payload: components["schemas"]["AnyJson"];
        };
        PgDbHealth: {
            /** Format: int64 */
            connActive: number;
            /** Format: int64 */
            connBlocked: number;
            /** Format: int64 */
            connIdle: number;
            /** Format: int64 */
            connIdleInTxn: number;
            /** Format: int64 */
            connIdleInTxnAborted: number;
            /** Format: int64 */
            connOther: number;
            /** Format: int64 */
            numBackends: number;
            /** Format: double */
            oldestQueryAge: number;
            /** Format: double */
            oldestTxnAge: number;
        };
        PruneResponse: {
            /** Format: int64 */
            pruned: number;
        };
        QueueOverview: {
            paused: boolean;
            queue: string;
            stats: components["schemas"]["QueueStats"];
            /** Format: int64 */
            workersLive: number;
            /** Format: int64 */
            workersPaused: number;
        };
        QueueRow: {
            createdAt: components["schemas"]["UTCTime"];
            metadata?: components["schemas"]["AnyJson"] | (never | null);
            paused: boolean;
            pausedAt?: components["schemas"]["UTCTime"] | (never | null);
            queueName: string;
            updatedAt: components["schemas"]["UTCTime"];
        };
        QueueStats: {
            /** Format: int64 */
            backoffJobs: number;
            /** Format: int64 */
            blockedJobs: number;
            /** Format: int64 */
            cancelledJobs: number;
            /** Format: int64 */
            dlqJobs: number;
            dlqKindCounts: {
                [key: string]: number;
            };
            /** Format: int64 */
            exhaustedJobs: number;
            /** Format: int64 */
            inFlightJobs: number;
            kindCounts: {
                [key: string]: number;
            };
            /** Format: double */
            oldestInFlightAgeSeconds: number | null;
            /** Format: double */
            oldestReadyAgeSeconds: number | null;
            /** Format: int64 */
            readyJobs: number;
            /** Format: int64 */
            scheduledJobs: number;
            /** Format: int64 */
            suspendedJobs: number;
            /** Format: int64 */
            throttledJobs: number;
            /** Format: int64 */
            totalJobs: number;
        };
        QueuesResponse: {
            queues: string[];
        };
        RateLimitBucketView: {
            /** Format: double */
            fillFraction: number | null;
            key: string;
            lastRefill: components["schemas"]["UTCTime"];
            /** Format: double */
            maxTokens: number;
            prefix: string;
            /** Format: double */
            tokens: number;
        };
        RateLimitBucketsResponse: {
            items: components["schemas"]["RateLimitBucketView"][];
        };
        RateLimitKey: {
            prefix: string;
            suffix: string;
        };
        RateLimitPoliciesResponse: {
            policies: components["schemas"]["RateLimitPolicyView"][];
        };
        RateLimitPolicyUpdate: {
            /** Format: double */
            overrideInterval?: number | null;
            /** Format: double */
            overrideMaxTokens?: number | null;
            /** Format: double */
            overrideRefillAmount?: number | null;
        };
        RateLimitPolicyView: {
            /** Format: double */
            avgTokens?: number | null;
            /** Format: int64 */
            bucketCount: number;
            /** Format: double */
            defaultInterval: number;
            /** Format: double */
            defaultMaxTokens: number;
            /** Format: double */
            defaultRefillAmount: number;
            /** Format: double */
            minTokens?: number | null;
            /** Format: double */
            overrideInterval?: number | null;
            /** Format: double */
            overrideMaxTokens?: number | null;
            /** Format: double */
            overrideRefillAmount?: number | null;
            prefix: string;
            /** Format: int64 */
            throttledCount: number;
            throttledQueues: string[];
        };
        RateLimitResetResponse: {
            /** Format: int64 */
            reset: number;
        };
        RescheduleRequest: {
            runAt: components["schemas"]["UTCTime"];
        };
        StatsResponse: {
            stats: components["schemas"]["QueueStats"];
            timestamp: string;
        };
        /**
         * Format: yyyy-mm-ddThh:MM:ssZ
         * @example 2016-07-22T00:00:00Z
         */
        UTCTime: string;
        /**
         * Format: uuid
         * @example 00000000-0000-0000-0000-000000000000
         */
        UUID: string;
        /** @enum {string} */
        WorkerHealth: "live" | "stale" | "draining";
        WorkerRow: {
            health: components["schemas"]["WorkerHealth"];
            hostName?: string | null;
            lastHeartbeat: components["schemas"]["UTCTime"];
            metadata?: components["schemas"]["AnyJson"] | (never | null);
            paused: boolean;
            queueName: string;
            shuttingDown: boolean;
            /** Format: double */
            staleThresholdSecs: number;
            startedAt: components["schemas"]["UTCTime"];
            /** Format: int32 */
            workerCount?: number | null;
            workerId: components["schemas"]["UUID"];
        };
        WorkersResponse: {
            workers: components["schemas"]["WorkerRow"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
