CREATE TABLE IF NOT EXISTS "arbiter"."golden_jobs_archive" (
  id BIGSERIAL PRIMARY KEY,
  completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  archive_expires_at TIMESTAMPTZ NOT NULL,
  job_id BIGINT NOT NULL,
  claimed_by UUID,
  archive_for INT,
  rate_limit_key TEXT,
  rate_limit_prefix TEXT,
  rate_limit_cost DOUBLE PRECISION,
  concurrency_key TEXT,
  concurrency_prefix TEXT,
  result JSONB,
  payload JSONB NOT NULL,
  group_key TEXT,
  inserted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ,
  last_attempted_at TIMESTAMPTZ,
  not_visible_until TIMESTAMPTZ,
  attempts INT NOT NULL DEFAULT 0,
  last_error TEXT,
  priority INT NOT NULL DEFAULT 0,
  dedup_key TEXT,
  dedup_strategy TEXT,
  max_attempts INT,
  parent_id BIGINT,
  parent_state JSONB,
  suspended BOOLEAN NOT NULL DEFAULT FALSE

);
