name: Haddock Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: '9.14'
          cabal-version: '3.14'

      - name: Cache
        uses: actions/cache@v5
        with:
          path: |
            ${{ steps.setup.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-${{ hashFiles('**/*.cabal', 'cabal.project') }}-v2
          restore-keys: |
            ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-

      - name: Build
        run: |
          cabal update
          cabal build all
          curl -L -O https://hackage.haskell.org/package/kedgeree-0.1.0/candidate/kedgeree-0.1.0.tar.gz
          tar xzf kedgeree-0.1.0.tar.gz
          cd kedgeree-0.1.0
          cabal install --project-dir=.

      - name: Generate Haddocks
        run: cabal haddock-project --hackage --haddock-options=--quickjump

      - name: Cook the haddocks
        run: |
          kedgeree ./haddocks --landing "Arbiter" --landing-description "Distributed job processing in Haskell, backed by your own PostgreSQL database"

      - name: Add the landing page
        run: |
          mv haddocks/index.html haddocks/packages.html
          cp -r site/. haddocks/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: haddocks

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
